version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: generate-app
          command: npm run generate
      - persist_to_workspace:
          root: ./dist
          paths:
            - ./*
  deploy:
    machine:
      enabled: true
    working_directory: ~/project
    steps:
      - add_ssh_keys:
          fingerprints:
            - "04:7f:0e:39:62:9c:06:0a:6d:9a:ce:0e:0f:a0:e4:ba"
      - attach_workspace:
          at: ./dist
      - run:
          name: remove-previous-deployed
          command: ssh ${SSH_USER}@${SSH_HOST} "cd /home/xpaperchallenge/www && ls | grep -v nlp | grep -v cv | xargs rm -rf"
      - run:
          name: copy-app-to-remote
          command: scp -r ./dist/* ${SSH_USER}@${SSH_HOST}:/home/xpaperchallenge/www
workflows:
  version: 2
  build-and-deploy: # deploy only from master branch
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - build
